#!/usr/bin/env ruby

$LOAD_PATH.push "./lib"

require "lexer"
require "parser"
require "formatter"

content = File.read(ARGV[0])

tokens = Lexer::tokenize(content)
# # puts ast
# # begin
parser = Parser.new(tokens, content)
File.write ARGV[0], Formatter.new(parser.parse!).eval
# rescue Exception => e
#   puts e.stack
#   puts "---- FAILED ----"
# end
