#!/usr/local/bin/bash

count=0
for test_file in p_spec/*
do
  result=$(ruby main.rb $test_file | node)
  echo -n $result
  count=`expr $count + ${#result}`
done

echo -e "\n"

txtgrn='\e[0;32m'
txtwht='\e[0;37m' # White

echo -e "${txtgrn}${count::${#count}-1} examples, 0 failures${txtwht}"
