#!/usr/bin/env ruby

$LOAD_PATH.push "/Users/marcelrusu/Documents/Projects/peacock/lib"

require "lexer"
require "parser"
require "compiler"

HTML_OUTPUT_FILENAME = ARGV[1] || "public/index.html"

while true
  content = File.read(ARGV[0])
  tokens = Lexer::tokenize(content)
  ast = Parser.new(tokens).parse!
  output = Compiler.new(ast).eval
  # output = File.read("./test.js")
  # remove node specific lines.. todo, compiler shouldn't have this in there..
  output = output.split("\n")
    .filter { |line| !["module.exports", "require"].any? { |k| line.include? k } }.join "\n"
  html = <<-EOS
  <html>
    <head>
      <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
      <meta content="utf-8" http-equiv="encoding">
      <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+Antique:wght@300&amp;display=swap" rel="stylesheet">
    </head>
    <body style="margin: 0">
      <div id="main"></div>
    </body>
    <script>#{output}</script>
    <style>
      body {
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
      }
    </style>
  </html>
  EOS

  File.write(HTML_OUTPUT_FILENAME, html)
  sleep 0.5
  # break
end
