#!/usr/bin/env ruby

$LOAD_PATH.push "./lib"

require "lexer"
require "parser"
require "compiler"

content = File.read(ARGV[0])
tokens = Lexer::tokenize(content)
ast = Parser.new(tokens).parse!
output = Compiler.new(ast).eval
# remove node specific lines.. todo, compiler shouldn't have this in there..
output = output.split("\n")
  .filter { |line| !["module.exports", "require"].any? { |k| line.include? k } }.join "\n"
html = <<-EOS
<html>
  <body></body>
  <script>#{output}</script>
</html>
EOS

HTML_OUTPUT_FILENAME = ARGV[1] || "output.html"

File.write(HTML_OUTPUT_FILENAME, html)
